context:
  version: 1.0.8

package:
  name: write-good
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/write-good/-/write-good-${{ version }}.tgz
  sha256: f54db3db8db0076fd1c05411c7f3923f055176632c51dc4046ab216e51130221

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - write-good --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Naive linter for English prose
  homepage: https://github.com/btford/write-good
  repository: https://github.com/btford/write-good

extra:
  recipe-maintainers:
    - danielnachun
